filter = "include/"
sort = "uncovered-percent"
print-summary = "yes"
exclude-unreachable-branches = "yes"
exclude-function-lines = "yes"
exclude-noncode-lines = "yes"
exclude-throw-branches = "yes"
html-medium-threshold = "80.0"
html-high-threshold = "90.0"
