name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.12" }

    - name: Install Catch2/GCovr
      run: |
        sudo apt-get update
        sudo apt-get install catch2 --yes --quiet
        pip install gcovr

    - name: Install LLVM
      if: matrix.compiler == 'clang++'
      run: |
        sudo apt-get install llvm --yes --quiet

    - name: Configure CMake
      run: >
        cmake
        -B ${{github.workspace}}/build
        -S ${{github.workspace}}
        -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
        -DCMAKE_INSTALL_PREFIX=/usr

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: Coverage
      run: cmake --build ${{github.workspace}}/build --target coverage

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix prefix

    - name: Pack
      working-directory: ${{github.workspace}}/build
      run: cpack -G TXZ

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: ${{github.workspace}}/build/coverage
        name: coverage-${{matrix.compiler}}
